pipeline {
  agent {
    kubernetes {
      inheritFrom 'deploy-users'
      defaultContainer 'helm'
      namespace 'fastapi-microservices'
      serviceAccount 'users-deployer'
    }
  }

  environment {
    CHART_PATH = 'helm/users'
    NAMESPACE = 'fastapi-microservices'
    RELEASE_NAME = 'orders-release'
    IMAGE_REPO = 'inestmimi123/k-orders'
    IMAGE_TAG = "${BUILD_NUMBER}-${GIT_COMMIT.take(7)}"
  }

  stages {
    stage('Debug Infos') {
      steps {
        sh '''
          echo "DEBUG: Deploying service 'orders'"
          echo "Namespace: ${NAMESPACE}"
          echo "Chart path: ${CHART_PATH}"
          echo "Image: ${IMAGE_REPO}:${IMAGE_TAG}"
        '''
      }
    }

    stage('Deploy users Service') {
      steps {
        sh '''
           helm upgrade --install orders-deploy ./helm/orders  -f ./helm/orders/values.yaml --namespace fastapi-microservices
        '''
      }
    }
  }

  post {
    success {
      echo "Déploiement réussi de orders"
    }
    failure {
      echo "Échec du déploiement de orders"
    }
  }
}
