pipeline {
  agent {
    kubernetes {
      inheritFrom 'deploy-users'
      defaultContainer 'helm'
      namespace 'fastapi-microservices'
      serviceAccount 'users-deployer'
    }
  }

  environment {
    CHART_PATH = 'helm/users'
    NAMESPACE = 'fastapi-microservices'
    RELEASE_NAME = 'users-release'
    IMAGE_REPO = 'inestmimi123/fastapi-users'
    IMAGE_TAG = "${BUILD_NUMBER}-${GIT_COMMIT.take(7)}"
  }

  stages {
    stage('Debug Infos') {
      steps {
        sh '''
          echo "DEBUG: Deploying service 'users'"
          echo "Namespace: ${NAMESPACE}"
          echo "Chart path: ${CHART_PATH}"
          echo "Image: ${IMAGE_REPO}:${IMAGE_TAG}"
        '''
      }
    }

    stage('Deploy users Service') {
      steps {
        sh '''
          helm upgrade --install ${RELEASE_NAME} ${CHART_PATH} \
            --namespace ${NAMESPACE} \
            --create-namespace \
            --set image.repository=${IMAGE_REPO} \
            --set image.tag=${IMAGE_TAG} \
            --wait
        '''
      }
    }

    stage('Verify') {
      steps {
        sh '''
          echo "Déploiement terminé pour 'users' dans le namespace '${NAMESPACE}'"
          kubectl get pods -n ${NAMESPACE}
        '''
      }
    }
  }

  post {
    success {
      echo "Déploiement réussi de users"
    }
    failure {
      echo "Échec du déploiement de users"
    }
  }
}
