version: '3.7'

services:
    gateway:
        image: ines/k-api-gateway:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: gateway-service
            dockerfile: Dockerfile
        env_file:
            - gateway-service/.env
        ports:
          - 8001:8000
        depends_on:
          - users
          - orders
        volumes:
          - ./gateway-service:/app

    users:
        image: ines/k-users:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: users-service
            dockerfile: Dockerfile
        env_file:
            - users-service/.env
        volumes:
          - ./users-service:/app

    orders:
        image: ines/k-orders:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: orders-service
            dockerfile: Dockerfile
        env_file:
            - orders-service/.env
        volumes:
          - ./orders-service:/app
