version: '3.7'

services:
    gateway:
        image: ines/k-api-gateway:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: gateway_service
            dockerfile: Dockerfile
        env_file:
            - gateway_service/.env
        ports:
          - 8001:8000
        depends_on:
          - users
          - orders
        volumes:
          - ./gateway_service:/app

    users:
        image: ines/k-users:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: users_service
            dockerfile: Dockerfile
        env_file:
            - users_service/.env
        volumes:
          - ./users_service:/app

    orders:
        image: ines/k-orders:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: orders_service
            dockerfile: Dockerfile
        env_file:
            - orders_service/.env
        volumes:
          - ./orders_service:/app
