apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-artifacts-pvc
  namespace: fastapi-microservices
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-py-cache-pvc
  namespace: fastapi-microservices
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi