apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: fastapi-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:community
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
              value: "true"
          volumeMounts:
            - name: sonar-data
              mountPath: /opt/sonarqube/data
            - name: sonar-extensions
              mountPath: /opt/sonarqube/extensions
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data-pvc
        - name: sonar-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: fastapi-microservices
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090